### ISSUE TITLE
What will this package do?

### ISSUE THREAD

**Issue by njtierney** [njtierney/datadevtools#1]
The tidyverse has made package development a lot easier. In the past, there was a lot of work with using tools like `package.skeleton`, the pseudo-latex for documentation of each R function, and so on. This made it hard to create high quality R packages. There was a lot of manual work to make sure that things were documented properly. That has now been made easier thanks to `devtools`, and `roxygen2`. More people can now quite easily write a high quality package.

We are still in the past a bit with the current state of data sharing tools. There is the same opportunity here with data tooling as there was with package development tools like `devtools`. Some features that such a tools to add:

* Add Metadata file
* Add a README (and paste the metadata file here)
* Add attribution/citation information
* Add data appropriate licenses
* Share on a cloud service
* Perform general data formatting checks
* Run checks on the data source

The README could be built up using blocks that insert tables and stuff.

So you could have a function that's like:

`insert_metadata_tbl("metadata-dat1")`

And this finds a file called `metadata-dat1` and inserts it into the README document.

This means that you don't need to worry about cutting + pasting the tables in, as it would be automated.

See for example the [incarceration trends data from tidy tuesday](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-01-22), where they show the data files and data dictionaries. These could maybe be stored in separate files and then printed out using one of these `insert` functions?

**Comment by karthik** [comment]
Also submit to Zenodo (from the Zenodo package)

**Comment by njtierney** [comment]
this info is summarised in the README and the relevant parts have been extracted into separate issues
